### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by Mi-Przystupa** [SamuelePolimi/romi#1]
Great library, but it would be helpful if there were some code snippet examples on how to use different components

**Comment by SamuelePolimi** [comment]
Thanks, Michael...
I always used it for myself (and it is so small that I wouldn't call it
even a library).

Please tell me what you need :D

Best,
Samuele.
Dr.-Ing. Samuele Tosatto
Postdoc @ University of Alberta
institutional email: ***@***.***

**Comment by Mi-Przystupa** [comment]
Thanks Dr. Tosatto for your quick reply!

I just think a small code snippet in the readme on how to create one of the MotorPrimitives and train it would be invaluable for your library. I'm sure you're busy though, and as you said it probably isn't too hard to figure out.

**Comment by Mi-Przystupa** [comment]
It could be cleaned up, but maybe something like this:
```
import romi.movement_primitives as mp
from romi.groups import Group
import romi.trajectory as traj
import numpy as np
import matplotlib.pyplot as plt

#Create trajectories
ths = np.linspace(0.0, 2.0 * np.pi, 100).reshape(-1, 1)

ths = np.repeat(ths, repeats=10, axis=1).T
print(ths.shape)


y = np.sin(ths)
for i in range(10):
    y[i] = np.sin(ths[i] * (i +1) *0.15)

#Give a group name with reference
group = Group("movement", refs=["y"])
mov_space = mp.ClassicSpace(group, n_features = 30 )

#learn motor prims
motorprims = []
for i in range(10):
    th_i = ths[i].reshape(-1, 1)
    y_i = y[i].reshape(-1, 1)
    
    sin_traj = traj.NamedTrajectoryBase(refs=['y'],
                                        durations=th_i,
                                        values=y_i)


    motorprims.append(mp.LearnTrajectory(mov_space, sin_traj)
                     )
#after learning primitives create probabilistic version
proMP = mp.ProbabilisticMovementPrimitives(mov_space, motorprims)

#visualize results
for mc in range(30):
    new_motion = proMP.sample_movement()
    new_m_traj = new_motion.get_full_trajectory(frequency=100, duration = 1.0)
    y_hat = []
    for y_h in new_m_traj:
        y_hat.append(y_h[0]['y'])
    
    plt.plot(y_hat, 'b', alpha = 0.1)

**Comment by SamuelePolimi** [comment]
Hi,

I added an example directory with an example of how to use the ProMPs.

You are completely right, without an example, this code is impossible to
use.

Best,
Samuele

Dr.-Ing. Samuele Tosatto
Postdoc @ University of Alberta
institutional email: ***@***.***
